server:
  port: 9898
spring:
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 1000Mb
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
      url: bolt://114.115.207.190:7687
      username: neo4j
      password: 123456
  datasource:
      url: jdbc:mysql://114.115.207.190:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 1Q2w3e4r.
      hikari:
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 60000
        is-auto-commit: true
        max-pool-size: 8
        min-idle: 2

mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql 
#--------七牛云配置
qiniu:
  access:
    key: 2J5BOKpbxDlzkYVYZ5dwGS3jAevVmOJwcL3fIdpw
  secret:
    key: 2LXAQbFFbFR_I76bseNEmu-Sjnh4RRaSRsazX5Dj
  bucket:
    name: nndt
    host:
      name: file.miaoleyan.com
  prefixName: /nndt
#--------七牛云配置
img:  #//如果是Windows情况下，格式是 D:\\blog\\image\\   linx 格式"/home/blog/image/";
   location : /home/blog/image/
file:
  serverurl:  http://localhost:8089
  location : /home/kgmanager/   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/";